// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKjencR4uE40Sv9TUGw7fRv6l0DTMTAG4',
    appId: '1:946187366202:web:8a877e4518a980c468ea03',
    messagingSenderId: '946187366202',
    projectId: 'portfolio-db4ee',
    authDomain: 'portfolio-db4ee.firebaseapp.com',
    storageBucket: 'portfolio-db4ee.appspot.com',
    measurementId: 'G-NCBHN6K19V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK5IE6fBAkxqQmYI_OCel0nD5pSjuiKDg',
    appId: '1:946187366202:android:63aff686cff8a2ad68ea03',
    messagingSenderId: '946187366202',
    projectId: 'portfolio-db4ee',
    storageBucket: 'portfolio-db4ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFjtiPVnUeiQhXnVYCWxBBP0JqrFg6X4k',
    appId: '1:946187366202:ios:9ac8441bda6a0d5768ea03',
    messagingSenderId: '946187366202',
    projectId: 'portfolio-db4ee',
    storageBucket: 'portfolio-db4ee.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFjtiPVnUeiQhXnVYCWxBBP0JqrFg6X4k',
    appId: '1:946187366202:ios:9ac8441bda6a0d5768ea03',
    messagingSenderId: '946187366202',
    projectId: 'portfolio-db4ee',
    storageBucket: 'portfolio-db4ee.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKjencR4uE40Sv9TUGw7fRv6l0DTMTAG4',
    appId: '1:946187366202:web:b2901278d3f282a568ea03',
    messagingSenderId: '946187366202',
    projectId: 'portfolio-db4ee',
    authDomain: 'portfolio-db4ee.firebaseapp.com',
    storageBucket: 'portfolio-db4ee.appspot.com',
    measurementId: 'G-M9H4VYMH6K',
  );
}
